# Generated by Django 3.2.9 on 2021-12-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_start'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
