# Generated by Django 3.2.9 on 2021-12-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_enroll_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
    ]
