# Generated by Django 3.2.9 on 2021-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_feature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='event',
            name='features',
            field=models.ManyToManyField(related_name='events', to='events.Feature', verbose_name='Особенность'),
        ),
    ]
