# Generated by Django 3.2.9 on 2022-01-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
